[project]
name = "finance-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.3.6",
    "openai>=2.11.0",
    "python-dotenv>=1.2.1",
]

[tool.uv]
package = true

[tool.uv.sources]
finance_agent = { path = "src/finance_agent" }
